### ISSUE TITLE
Incohérence affichage des volumes m3 avec Domoticz 

### ISSUE THREAD

**Issue by dranreb38** [Scrat95220/DomoticzGazpar#20]
J'ai un problème d'incohérence dans les unités de mesure avec de l'import des données.
![Screenshot_344](https://user-images.githubusercontent.com/16446911/146055687-d26228a2-5d4b-4b5e-851e-a1a237757337.png)
![Screenshot_345](https://user-images.githubusercontent.com/16446911/146055768-137ae054-2018-418c-9394-2fc550682e1b.png)

Fichier log de DomoticzGazpar
![Screenshot_347](https://user-images.githubusercontent.com/16446911/146055978-2c344e25-96d3-438a-9635-1f0f29dda588.png)
Requête SQL
![Screenshot_348](https://user-images.githubusercontent.com/16446911/146056038-e68e238c-0584-4b5b-8eaa-8ad6a70a0c97.png)

Est-ce un problème de conf de mon domoticz ?
![Screenshot_350](https://user-images.githubusercontent.com/16446911/146056494-76f195bb-84ce-4ed5-b2e5-c8b74c9bc592.png)

**Comment by Scrat95220** [comment]
Essai de mettre "1" dans la partie Gaz

**Comment by dranreb38** [comment]
J'avais déjà fais la motif , c'est idem 
![Screenshot_351](https://user-images.githubusercontent.com/16446911/146088043-345e4f10-82f2-466b-90d0-42e6cd8a13d9.png)
Par contre si je multiplie la donnée par 1000 c'est OK.

**Comment by Scrat95220** [comment]
Tu as bien un counter de type "Gas" ?
![image](https://user-images.githubusercontent.com/33357657/146088392-cb0593a2-06f7-4368-99a9-6df2b580f92f.png)

**Comment by dranreb38** [comment]
Oui je confirme
![Screenshot_354](https://user-images.githubusercontent.com/16446911/146089491-687d457f-6e9d-4e8f-8a15-0b319d741470.png)

![Screenshot_353](https://user-images.githubusercontent.com/16446911/146089461-fb1b1752-b151-4360-a5ac-12f5e1ffda0d.png)

**Comment by onlinux** [comment]
Too much merge requests accepted without any fully checkouts.
Quote -> domoticz/API  :

> /json.htm?type=command&param=udevice&idx=IDX&nvalue=0&svalue=USAGE
> USAGE= Gas usage in liter (1000 liter = 1 m³)
> So if your gas meter shows f.i. 145,332 m³ you should send 145332.
> The USAGE is the total usage in liters from start, not f.i. the daily usage.

Volume should be * 1000.

It's  a mess now, update db with sqlite3 module mixed up with url access to domoticz.

I guess you should downgrade the project and split it up into 2 branches or make 2 gazpar.py versions

- gazpar.py sqilte3 update version which runs on localhost
- gazpar.py url domoticz update version which can run on any host on lan or wan if you accept https merge request.

Have a view to my branch which sticks up to sqlite3 update (https://github.com/onlinux/DomoticzGazpar) which gives me all satisfactions.

Thank you anyway for this new version ( v1.2.2)  and sqlite3 db  which runs like a charm for me.

**Comment by dranreb38** [comment]
Hello, @onlinux & @Scrat95220 
La version de @onlinux  est **OK** ! il faut bien *1000 
**Thank @onlinux**  
Je vais modifier les valeurs importées et multiplier par 1000
Merci pour votre travail , tout me semble correct

**Comment by pbda** [comment]
Moi aussi j'ai des données incohérentes depuis l'update par url Domoticz. La version de @onlinux fonctionne mais je ne comprends pas à quoi servent les configurations suivantes qui semblent être sans effet:
```
[DOMOTICZ_SETTINGS]
DB_PATH=/home/pi/domoticz

[loggers]
keys=root

[handlers]
keys=consoleHandler,fileHandler,httpHandler

[formatters]
keys=formatter

[logger_root]
level=DEBUG
handlers=fileHandler,httpHandler

[handler_httpHandler]
# Add log messages to domoticz logfile
# Access domoticz via Domoticz API/JSON URL's
class=domoticzHandler.domoticzHandler
args=('localhost:8080','GAZPAR')
level=INFO

[handler_fileHandler]
class=FileHandler
level=DEBUG
formatter=formatter
args=('%(logfilename)s',)

[handler_consoleHandler]
class=StreamHandler
level=INFO
formatter=formatter
args=(sys.stdout,)

[formatter_formatter]
format=%(asctime)s - %(levelname)s - %(message)s

```

**Comment by onlinux** [comment]
Les différents paramètres permettent d'avoir le choix de plusieurs supports pour les logs.
fileHandler -> fichier domoticz_gazpar.log
httpHandler -> log domoticz 
consoleHandler -> console lors du lancement gazpar.py pour tests
avec choix du niveau de logging dans les paramètres. INFO,WARNING,ERROR,CRITICAL

Si vous ne changez rien aux paramètres formatter, vous devriez avoir le fichier domoticz_gazpar.log en DEBUG
et la log domoticz en [INFO](https://github.com/onlinux/DomoticzGazpar/blob/main/images/domoticzLog.png)
![domoticzLog](https://user-images.githubusercontent.com/1698503/146178366-b3a2a114-cee5-4e77-9bda-135dc0f32000.png)

**Comment by Scrat95220** [comment]
> Too much merge requests accepted without any fully checkouts. Quote -> domoticz/API :
> 
> > /json.htm?type=command&param=udevice&idx=IDX&nvalue=0&svalue=USAGE
> > USAGE= Gas usage in liter (1000 liter = 1 m³)
> > So if your gas meter shows f.i. 145,332 m³ you should send 145332.
> > The USAGE is the total usage in liters from start, not f.i. the daily usage.
> 
> Volume should be * 1000.
> 
> It's a mess now, update db with sqlite3 module mixed up with url access to domoticz.
> 
> I guess you should downgrade the project and split it up into 2 branches or make 2 gazpar.py versions
> 
> * gazpar.py sqilte3 update version which runs on localhost
> * gazpar.py url domoticz update version which can run on any host on lan or wan if you accept https merge request.
> 
> Have a view to my branch which sticks up to sqlite3 update (https://github.com/onlinux/DomoticzGazpar) which gives me all satisfactions.
> 
> Thank you anyway for this new version ( v1.2.2) and sqlite3 db which runs like a charm for me.

Personnally i didn't need to *1000 for to have the correct values in my m3 sensor and the last merges didn't  created any issues on my side. Maybe it depend to the domoticz/sensor settings.
Concerning the mix of  the JSON API usage et the db update via sqlite, in my point of view it's better tu use only the official API rather than the db update because on my side it caused some db lock errors when other sensor tried to update values during the grdf data insertion via sqlite. But unfortunately the last seen info was not up to date via this API JSON

**Comment by dranreb38** [comment]
Hello, @onlinux & @Scrat95220
Merci pour votre travail, les données remontent bien. J'ai juste une interrogation au sujet des stats annuel , je n'ai pas pris le temps de regarder mais visiblement le calcul annuel ne se fait pas....

![Screenshot_357](https://user-images.githubusercontent.com/16446911/146530279-c959054f-9e0d-4ed2-8da0-fe2a73f8e2be.png)

**Comment by onlinux** [comment]
Étonnant, je n'ai pas cette option d'affichage disponible sur ma version domoticz v2020.2 !

**Comment by dranreb38** [comment]
Je suis en Version: 2021.1 (build 13916)

**Comment by Scrat95220** [comment]
Je suis en version 2021.1 également et je n'ai pas cette vue non plus ...

**Comment by dranreb38** [comment]
? Curieux çà, j'ai les même affichage pour le Linky, visiblement c'est depuis la dernière version de Domoticz.

![Screenshot_358](https://user-images.githubusercontent.com/16446911/146634824-31f8b3ad-0deb-4947-b5b3-c2e62fc8c19a.png)

**Comment by onlinux** [comment]
Bonjour à tous,

J'ai créé un fichier custom_icons.zip qui peut être téléchargé depuis domoticz et qui inclu le logo Grdf gazpar.

![gazparDevicekWh](https://user-images.githubusercontent.com/1698503/146673578-01b75054-7035-4184-8d46-3579ed8da507.png)

Le fichier est disponible ici [https://github.com/onlinux/DomoticzGazpar](url)

Scrat95220 , je suis  désolé de ne pas proposer un request merge, car je suis resté sur la branche qui update la base de données domoticz avec sqlite3. J'ai mis à jour aussi le README.md

**Comment by dranreb38** [comment]
@onlinux ,

Je ne peux pas ouvrir un ticket sur ton git, j'ai une erreur suite réinstallation de mon domiticz update
`root@domoticz:/home/pi/domoticz/DomoticzGazpar# python3 gazpar.py
Traceback (most recent call last):
  File "gazpar.py", line 234, in <module>
    main()
  File "gazpar.py", line 226, in main
    dtostr(today))
  File "gazpar.py", line 120, in updatedb
    j = json.loads(resp3.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
root@domoticz:/home/pi/domoticz/DomoticzGazpar#
`

**Comment by onlinux** [comment]
Bonjour,

il semblerait qu'il y ait un souci au niveau de l'appel suivant:

> resp3 = session.get(
>         'https://monespace.grdf.fr/api/e-connexion/users/pce/historique-consultation')

Dans la log debug, tu devrais avoir le retour affiché :

    logging.debug("Get NumPce: %s", resp3.text)

**Comment by dranreb38** [comment]
Voici la log de domoticz_gazpar.log
`2021-12-24 12:24:12,339 - DEBUG - Get configuration
2021-12-24 12:24:12,342 - DEBUG - Database is /home/pi/domoticz/domoticz.db
2021-12-24 12:24:12,343 - INFO - logging in as xxxxxx.
2021-12-24 12:24:12,360 - DEBUG - Starting new HTTPS connection (1): login.monespace.grdf.fr:443
2021-12-24 12:24:12,651 - DEBUG - https://login.monespace.grdf.fr:443 "POST /sofit-account-api/api/v1/auth HTTP/1.1" 200 None
2021-12-24 12:24:12,660 - DEBUG - Starting new HTTPS connection (1): monespace.grdf.fr:443
2021-12-24 12:24:12,822 - DEBUG - https://monespace.grdf.fr:443 "GET / HTTP/1.1" 302 138
2021-12-24 12:24:12,832 - DEBUG - Starting new HTTPS connection (1): sofa-connexion.grdf.fr:443
2021-12-24 12:24:13,026 - DEBUG - https://sofa-connexion.grdf.fr:443 "GET /openam/oauth2/externeGrdf/authorize?response_type=code&scope=openid+profile+email+infotravaux+/v1/accreditation+/v1/accreditations+/digiconso/v1+/digiconso/v1/consommations+new_meg+/Demande.read+/Demande.write&client_id=prod_espaceclient&state=0&redirect_uri=https://monespace.grdf.fr/_codexch&nonce=adTmEyFt-AyAWbQSxaifFGmVAY0KhDlnm0JSV5PZSKI&by_pass_okta=1&capp=meg HTTP/1.1" 302 0
2021-12-24 12:24:13,079 - DEBUG - https://login.monespace.grdf.fr:443 "GET /mire/connexion?goto=https%3A%2F%2Fsofa-connexion.grdf.fr%3A443%2Fopenam%2Foauth2%2FexterneGrdf%2Fauthorize%3Fresponse_type%3Dcode%26scope%3Dopenid%2520profile%2520email%2520infotravaux%2520%252Fv1%252Faccreditation%2520%252Fv1%252Faccreditations%2520%252Fdigiconso%252Fv1%2520%252Fdigiconso%252Fv1%252Fconsommations%2520new_meg%2520%252FDemande.read%2520%252FDemande.write%26client_id%3Dprod_espaceclient%26state%3D0%26redirect_uri%3Dhttps%253A%252F%252Fmonespace.grdf.fr%252F_codexch%26nonce%3DadTmEyFt-AyAWbQSxaifFGmVAY0KhDlnm0JSV5PZSKI%26by_pass_okta%3D1%26capp%3Dmeg&realm=/externeGrdf&capp=meg HTTP/1.1" 200 836
2021-12-24 12:24:13,082 - INFO - logged in successfully!
2021-12-24 12:24:13,086 - DEBUG - retrieving data...
2021-12-24 12:24:13,087 - DEBUG - start_date: 2021-11-24
2021-12-24 12:24:13,087 - DEBUG -   end_date: 2021-12-24
2021-12-24 12:24:13,120 - DEBUG - https://monespace.grdf.fr:443 "GET /api/e-connexion/users/pce/historique-consultation HTTP/1.1" 302 138
2021-12-24 12:24:13,168 - DEBUG - https://sofa-connexion.grdf.fr:443 "GET /openam/oauth2/externeGrdf/authorize?response_type=code&scope=openid+profile+email+infotravaux+/v1/accreditation+/v1/accreditations+/digiconso/v1+/digiconso/v1/consommations+new_meg+/Demande.read+/Demande.write&client_id=prod_espaceclient&state=0&redirect_uri=https://monespace.grdf.fr/_codexch&nonce=DmTwyx848RNtqnMiU3yIxs0mbs_IGBkxHyAptSfW-ek&by_pass_okta=1&capp=meg HTTP/1.1" 302 0
2021-12-24 12:24:13,216 - DEBUG - https://login.monespace.grdf.fr:443 "GET /mire/connexion?goto=https%3A%2F%2Fsofa-connexion.grdf.fr%3A443%2Fopenam%2Foauth2%2FexterneGrdf%2Fauthorize%3Fresponse_type%3Dcode%26scope%3Dopenid%2520profile%2520email%2520infotravaux%2520%252Fv1%252Faccreditation%2520%252Fv1%252Faccreditations%2520%252Fdigiconso%252Fv1%2520%252Fdigiconso%252Fv1%252Fconsommations%2520new_meg%2520%252FDemande.read%2520%252FDemande.write%26client_id%3Dprod_espaceclient%26state%3D0%26redirect_uri%3Dhttps%253A%252F%252Fmonespace.grdf.fr%252F_codexch%26nonce%3DDmTwyx848RNtqnMiU3yIxs0mbs_IGBkxHyAptSfW-ek%26by_pass_okta%3D1%26capp%3Dmeg&realm=/externeGrdf&capp=meg HTTP/1.1" 200 836
2021-12-24 12:24:13,218 - DEBUG - Get NumPce: <!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Mire de connexion</title>
  <base href="/mire/">
  <script type="text/javascript">
    var onloadCallback = function() {
      setTimeout(onloadCallback, 500)
    };
  </script>
  <meta name="viewport" content="width=device-height, initial-scale=1, maximum-scale=0.42">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  
</head>
<body>
  <app-root></app-root>
<script src="runtime.e7df24b5d39b2102df5c.js" defer></script><script src="polyfills.35a5ca1855eb057f016a.js" defer></script><script src="styles.b81fc9aa724cfcc4a2de.js" defer></script><script src="main.9d08f6b4bc08ba702548.js" defer></script></body>
</html>

2021-12-24 12:25:03,221 - DEBUG - Get configuration
2021-12-24 12:25:03,225 - DEBUG - Database is /home/pi/domoticz/domoticz.db
2021-12-24 12:25:03,225 - INFO - logging in as rouxb@free.fr...
2021-12-24 12:25:03,242 - DEBUG - Starting new HTTPS connection (1): login.monespace.grdf.fr:443
2021-12-24 12:25:03,557 - DEBUG - https://login.monespace.grdf.fr:443 "POST /sofit-account-api/api/v1/auth HTTP/1.1" 200 None
2021-12-24 12:25:03,565 - DEBUG - Starting new HTTPS connection (1): monespace.grdf.fr:443
2021-12-24 12:25:03,724 - DEBUG - https://monespace.grdf.fr:443 "GET / HTTP/1.1" 302 138
2021-12-24 12:25:03,736 - DEBUG - Starting new HTTPS connection (1): sofa-connexion.grdf.fr:443
2021-12-24 12:25:03,926 - DEBUG - https://sofa-connexion.grdf.fr:443 "GET /openam/oauth2/externeGrdf/authorize?response_type=code&scope=openid+profile+email+infotravaux+/v1/accreditation+/v1/accreditations+/digiconso/v1+/digiconso/v1/consommations+new_meg+/Demande.read+/Demande.write&client_id=prod_espaceclient&state=0&redirect_uri=https://monespace.grdf.fr/_codexch&nonce=CKc23VsqjweOorwkndY3GzSyHuw-LXPP6wphemjhUaY&by_pass_okta=1&capp=meg HTTP/1.1" 302 0
2021-12-24 12:25:03,980 - DEBUG - https://login.monespace.grdf.fr:443 "GET /mire/connexion?goto=https%3A%2F%2Fsofa-connexion.grdf.fr%3A443%2Fopenam%2Foauth2%2FexterneGrdf%2Fauthorize%3Fresponse_type%3Dcode%26scope%3Dopenid%2520profile%2520email%2520infotravaux%2520%252Fv1%252Faccreditation%2520%252Fv1%252Faccreditations%2520%252Fdigiconso%252Fv1%2520%252Fdigiconso%252Fv1%252Fconsommations%2520new_meg%2520%252FDemande.read%2520%252FDemande.write%26client_id%3Dprod_espaceclient%26state%3D0%26redirect_uri%3Dhttps%253A%252F%252Fmonespace.grdf.fr%252F_codexch%26nonce%3DCKc23VsqjweOorwkndY3GzSyHuw-LXPP6wphemjhUaY%26by_pass_okta%3D1%26capp%3Dmeg&realm=/externeGrdf&capp=meg HTTP/1.1" 200 836
2021-12-24 12:25:03,982 - INFO - logged in successfully!
2021-12-24 12:25:03,986 - DEBUG - retrieving data...
2021-12-24 12:25:03,986 - DEBUG - start_date: 2021-11-24
2021-12-24 12:25:03,987 - DEBUG -   end_date: 2021-12-24
2021-12-24 12:25:04,020 - DEBUG - https://monespace.grdf.fr:443 "GET /api/e-connexion/users/pce/historique-consultation HTTP/1.1" 302 138
2021-12-24 12:25:04,075 - DEBUG - https://sofa-connexion.grdf.fr:443 "GET /openam/oauth2/externeGrdf/authorize?response_type=code&scope=openid+profile+email+infotravaux+/v1/accreditation+/v1/accreditations+/digiconso/v1+/digiconso/v1/consommations+new_meg+/Demande.read+/Demande.write&client_id=prod_espaceclient&state=0&redirect_uri=https://monespace.grdf.fr/_codexch&nonce=oLOSvOGfoM5rQnAmNXBnoJnWe3uAQxFNQNCFppVEQGQ&by_pass_okta=1&capp=meg HTTP/1.1" 302 0
2021-12-24 12:25:04,136 - DEBUG - https://login.monespace.grdf.fr:443 "GET /mire/connexion?goto=https%3A%2F%2Fsofa-connexion.grdf.fr%3A443%2Fopenam%2Foauth2%2FexterneGrdf%2Fauthorize%3Fresponse_type%3Dcode%26scope%3Dopenid%2520profile%2520email%2520infotravaux%2520%252Fv1%252Faccreditation%2520%252Fv1%252Faccreditations%2520%252Fdigiconso%252Fv1%2520%252Fdigiconso%252Fv1%252Fconsommations%2520new_meg%2520%252FDemande.read%2520%252FDemande.write%26client_id%3Dprod_espaceclient%26state%3D0%26redirect_uri%3Dhttps%253A%252F%252Fmonespace.grdf.fr%252F_codexch%26nonce%3DoLOSvOGfoM5rQnAmNXBnoJnWe3uAQxFNQNCFppVEQGQ%26by_pass_okta%3D1%26capp%3Dmeg&realm=/externeGrdf&capp=meg HTTP/1.1" 200 836
2021-12-24 12:25:04,139 - DEBUG - Get NumPce: <!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Mire de connexion</title>
  <base href="/mire/">
  <script type="text/javascript">
    var onloadCallback = function() {
      setTimeout(onloadCallback, 500)
    };
  </script>
  <meta name="viewport" content="width=device-height, initial-scale=1, maximum-scale=0.42">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  
</head>
<body>
  <app-root></app-root>
<script src="runtime.e7df24b5d39b2102df5c.js" defer></script><script src="polyfills.35a5ca1855eb057f016a.js" defer></script><script src="styles.b81fc9aa724cfcc4a2de.js" defer></script><script src="main.9d08f6b4bc08ba702548.js" defer></script></body>
</html>

`

**Comment by onlinux** [comment]
Il y a un souci d'accès.
Normalement la log devrait donner cela:
DEBUG - https://monespace.grdf.fr:443 "GET / HTTP/1.1" 200 8916
2021-12-24 14:39:39,488 - INFO - logged in successfully!
2021-12-24 14:39:39,494 - DEBUG - retrieving data...
2021-12-24 14:39:39,495 - DEBUG - start_date: 2020-12-24
2021-12-24 14:39:39,495 - DEBUG -   end_date: 2021-12-24
2021-12-24 14:39:39,585 - DEBUG - https://monespace.grdf.fr:443 "GET
/api/e-connexion/users/pce/historique-consultation HTTP/1.1" *200 None *
2021-12-24 14:39:39,589 - DEBUG - Get NumPce:
[{"id":21916,"numPce":"xxxxxxxxxxxxx","updatedAt":"2021-12-24T13:54:53+01:00"}]

2021-12-24 14:39:40,022 - DEBUG - https://monespace.grdf.fr:443 "GET
/api/e-conso/pce/consommation/informatives?dateDebut=2020-12-24&dateFin=2021-12-24&pceList[]=xxxxxxxxxxx
HTTP/1.1" 200 None
2021-12-24 14:39:40,069 - INFO - Updating Database...
2021-12-24 14:39:40,072 - DEBUG - coeffConversion: 11.6
2021-12-24 14:39:40,077 - DEBUG - BEGIN
2021-12-24 14:39:40,078 - DEBUG - DELETE FROM Meter_Calendar WHERE
devicerowid = '293' and date = '2021-07-02'
2021-12-24 14:39:40,078 - DEBUG - INSERT INTO Meter_Calendar
(DeviceRowID,Value,Counter,Date) VALUES ('293',15000,40,'2021-07-02')
2021-12-24 14:39:40,078 - DEBUG - DELETE FROM Meter_Calendar WHERE
devicerowid = '294' and date = '2021-07-02'
2021-12-24 14:39:40,079 - DEBUG - INSERT INTO Meter_Calendar
(DeviceRowID,Value,Counter,Date) VALUES ('294',1294,25,'2021-07-02')

Le code retour normal est 200, pour toi le code retour est 302 (qui
signifie une redirection vers une autre page)

je suggérerais d'essayer de se connecter au ton compte grdf et voir s'il
n'est pas nécessaire de se re-identifier.

**Comment by dranreb38** [comment]
Effectivement sur la page https://monespace.grdf.fr, j’étais bien en présence d'un CAPCHA. Après validation c'est désormais ok.
il reste juste la maj pour le comptage en Kwh qui n'est pas correct.
![Screenshot_366](https://user-images.githubusercontent.com/16446911/147360533-06f4d448-740a-4515-81b3-7e1e6b3bb102.png)

![Screenshot_367](https://user-images.githubusercontent.com/16446911/147360545-6088920c-aab3-42f0-a6f4-47a3f1cda4b8.png)

**Comment by onlinux** [comment]
On va y arriver!

2021-12-24 16:58:37,157 - DEBUG - INSERT INTO Meter_Calendar
(DeviceRowID,Value,Counter,Date) VALUES ('294',6571,403,'2021-12-21')
2021-12-24 16:58:37,157 - DEBUG - UPDATE DeviceStatus SET lastupdate =
'2021-12-24 16:58:37' , sValue = 73000 WHERE id = '293'
2021-12-24 16:58:37,158 - DEBUG - UPDATE DeviceStatus SET lastupdate =
'2021-12-24 16:58:37' , sValue = 6571 WHERE id = '294'
[image: Screenshot_20211224_165749.png]
2021-12-24 16:58:37,158 - INFO - Database Total Changes: 26

La seule différence remarquable est le type device utilisé

General Managed Counteur  vs P1 Smart Meter Energy

**Comment by dranreb38** [comment]
Oui effectivement, erreur de ma part sur le choix du device. C'est correct mais j'ai l’impression que le site grdf et en train de mettre en place un system de CAPCHA pour valider la connexion. Obliger de me reconnecter via la page d'authentification

**Comment by Scrat95220** [comment]
> Oui effectivement, erreur de ma part sur le choix du device. C'est correct mais j'ai l’impression que le site grdf et en train de mettre en place un system de CAPCHA pour valider la connexion. Obliger de me reconnecter via la page d'authentification

A ce que j'avais remarqué la captcha était nécessaire que suite à une tentative de connexion avec erreur de mot de passe.

**Comment by empierre** [comment]
J'avais ouvert un autre ticket mais je vois que les mêmes soucis apparaissent ici aussi, données fausses pour moi, compteur principal en Général KWH et secondaire en Smartmeter P1 Gaz.

J'avais noté par le passé que les API rest ne permettent pas de mettre des données dans le passé, seules les insert en base (avec suppression de la période concernée auparavant) le permettent.

**Comment by empierre** [comment]
sinon domoticz par API fait les plus et les moins sur la même jour,ée:
![image](https://user-images.githubusercontent.com/7287178/148245503-831a41de-deb3-413a-9144-e5838220be48.png)

**Comment by empierre** [comment]
et quand je fais les inserts à la main des valeurs récupérées tout est bon dans le passé;
DELETE FROM 'Meter_Calendar' WHERE devicerowid=559 and date = '2021-12-19'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (559, '78000', '6859', '2021-12-19');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=559 and date = '2021-12-20'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (559, '74000', '6833', '2021-12-20');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=559 and date = '2021-12-21'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (559, '86000', '7019', '2021-12-21');

**Comment by empierre** [comment]
![image](https://user-images.githubusercontent.com/7287178/148246553-f2767d7e-9e3a-47de-a1a4-a3b239b6248c.png)

**Comment by empierre** [comment]
Donc je te recommande de revenir aux inserts SQL car il n'y a pas d'autre façon possible sur des données journalières ou arrivées en retard (comme c'est le cas sur ces archis de collecte)

**Comment by Scrat95220** [comment]
> Donc je te recommande de revenir aux inserts SQL car il n'y a pas d'autre façon possible sur des données journalières ou arrivées en retard (comme c'est le cas sur ces archis de collecte)

Bonsoir,
L'API JSON de domoticz permet bien de mettre à jour des données journalières passées. C'est ce qui est utilisé dans le script et cela fonctionne correctement avec un compteur de type "Managed Counter". Les valeurs des "x" derniers jours sont écrasés via l'API à chaque exécution du script

**Comment by empierre** [comment]
argh... ça va me faire perdre tout mon historique... les types ne sont pas
compatibles...

**Comment by empierre** [comment]
J'ai fait un petit script e migration d'un type à l'autre vaec la conversion des champs (inversés) et des valeurs 'il y en a intéressés.

Différence de rendu entre general KWH et Managed counter:
![image](https://user-images.githubusercontent.com/7287178/148507060-8f992430-7c00-4cf9-9d04-0d456a9e8465.png)

![image](https://user-images.githubusercontent.com/7287178/148507105-7026c04a-adf7-48b0-b979-b41792bee9d2.png)

**Comment by dranreb38** [comment]
@empierre , je veux bien tester ton script.

**Comment by Scrat95220** [comment]
@empierre , je suis également intéressé par ton script

**Comment by empierre** [comment]
Hello,

  J'ai poussé le script:

https://github.com/empierre/domoticz_gaspar/migrate.pl

  en  entrée id device source id device destination.

  ça génère un req.sql qu'il faut revoir avant d'insérer en base (  cat
req.sql | sqlite3 domoticz.db    )

  chez moi ça va du type général vers un managed counter.

**Comment by ldrolez** [comment]
Salut, j'utilise bien un 'managed counter' et les chiffres jour par jour sont ok. 
Mais, le total du mois ne correspond pas. Comment corriger cela?

**Comment by ldrolez** [comment]
Je confirme qu'il y a un mélange de Wh, kWh et m2 dans le code.

Par exemple `index = j[str(numPce)]['releves'][0]['indexDebut']` est en m2, et plus loin on a `index = index + conso` or conso est en kWh. Un peu plus bas on transforme la conso en Wh en multipliant par 1000, mais l'index reste en Wh.

On peut éventuellement utiliser indexDebut en multipliant par le coef correcteur, mais dans ce cas l'index mensuel serait précis qu'à 11kWh près... Donc la meilleure solution sera de recalculer l'index en kWh chaque mois en prenant l'historique de la DB Domoticz.

**Comment by Overnuts** [comment]
> Je confirme qu'il y a un mélange de Wh, kWh et m2 dans le code.
> 
> Par exemple `index = j[str(numPce)]['releves'][0]['indexDebut']` est en m2, et plus loin on a `index = index + conso` or conso est en kWh. Autre incohérence, un peu plus bas on transforme la conso en Wh en multipliant par 1000, mais l'index reste en kWh.
> 
> On peut éventuellement utiliser indexDebut en multipliant par le coef correcteur, mais dans ce cas l'index mensuel serait précis qu'à 11kWh près... Donc la meilleure solution sera de recalculer l'index en kWh chaque mois en prenant l'historique de la DB Domoticz.

Selon la doc de  https://www.domoticz.com/wiki/Domoticz_API/JSON_URL's#Managed_counter
si on mets "-1" comme valeur pour "COUNTER", le total est ignoré. je viens de faire un test dans un coin avec un nouveau compteur managé, il m'a injecté l'historique de grdf comme il fallait
![image](https://user-images.githubusercontent.com/61836209/191744581-ca941d01-ad79-42ac-aa03-0159290fd8aa.png)

![image](https://user-images.githubusercontent.com/61836209/191744491-8e8deaca-91bd-48b2-89ef-71890ff8548a.png)
