### ISSUE TITLE
Changement header grdf

### ISSUE THREAD

**Issue by syl2222** [Scrat95220/DomoticzGazpar#37]
Bonjour,

Un changement  a eu lieu chez grdf.
Il faut maintenant rajouter dans le header le domain (vu sur le github de homeassistant)

Je ne sais pas faire de pull request, du coup, scrat95220 , si tu passe par ici :)

Dans gazpar.py, lignes 94 à 96 , il faudrait rajouter une ligne:
'domain': 'grdf.fr', 

Normalement, ça suffit pour que tout refonctionne

A+

**Comment by ProfBoc75** [comment]
Bonjour,

Je confirme que l'ajout de cette ligne dans la zone Header corrige l'erreur 500: (entre les lignes 95 et 96)
'domain': 'grdf.fr',

A noter que mes dernières données sont au 6 Juillet  avec DomoticzGazpar ET dans mon espace GRDF.
Manque toutes les données depuis le 7 juillet, Pareil pour vous ?

**Comment by onlinux** [comment]
Idem

**Comment by pascal69480** [comment]
Et pareil également, plus rien sur le portail de suivi non plus depuis le 07/07 ... mais apparition subite d'une conso le 12/07

**Comment by Phil353556** [comment]
**Merci** @syl2222 et @ProfBoc75 j'ai ajouté la ligne et c'est tout bon.

**Comment by ProfBoc75** [comment]
> **Merci** @syl2222 et @ProfBoc75 j'ai ajouté la ligne et c'est tout bon. En revanché coté historique GrDF c'est largement perfectible ![ksnip_20220718-142714](https://user-images.githubusercontent.com/64729485/179510978-c522ff9a-7a3e-4b44-ac1b-6723468f5d0c.png)

De rien 👍 
Ils doivent avoir des soucis de traitement des données, j'ai aussi jusqu'au 13 Juillet, mais je n'ai pas eu toutes les dernières données en même temps, c'était du gruyère la semaine dernière, manquait des jours, c'est corrigé depuis mais plus rien depuis le 14 juillet.  wait n' c ...

**Comment by syl2222** [comment]
De mon côté, toujours Ko sur l'espace client grdf depuis le 14/07. Ce qui est intéressant, c'est que, quand je passe par mon fournisseur, j'ai bien des infos pour les jours après le 14.  Du coup, c'est que la consultation côté client qui va pas, la facturation, elle , elle marche :(

**Comment by usky73** [comment]
Bonjour, j'ai fait un git pull, la nouvelle version c'est mise à jour mais j'ai une erreur au lancement : 
`Traceback (most recent call last):
  File "/home/pi/domoticz/DomoticzGazpar/gazpar.py", line 276, in <module>
    main()
  File "/home/pi/domoticz/DomoticzGazpar/gazpar.py", line 260, in main
    token = login()
  File "/home/pi/domoticz/DomoticzGazpar/gazpar.py", line 102, in login
    print("Login call - error status :"+resp1.status_code+'\n');
TypeError: can only concatenate str (not "int") to str`

Une idée ?

**Comment by melufre** [comment]
change print("Login call - error status :"+resp1.status_code+'\n')
en print("Login call - error status :"+str(resp1.status_code)+'\n')
tu dois avoir une erreur  aussi dans ton mot de passe

**Comment by usky73** [comment]
Bonjour, j'ai modifié les lignes 102 et 103 avec le string mais toujours une erreur : 
`Login call - error status :500`

Je n'ai rien modifié au niveau de mes mots de passe depuis le 7 Juillet :-( tout est bon.
Une idée ?

**Comment by usky73** [comment]
Merci, corrigé. En fait j'ai l'erreur 500...
J'ai pourtant fait un git pull pour mettre le python à jour, mais il semble que cela ne soit pas (encore) à jour.
Et gazpar.py a bien été modifié mais pas avec cette modif, c'est normal ?

Sinon, j'ai fait la modif du header, ca marche.

**Comment by ProfBoc75** [comment]
> Merci, corrigé. En fait j'ai l'erreur 500... J'ai pourtant fait un git pull pour mettre le python à jour, mais il semble que cela ne soit pas (encore) à jour. Et gazpar.py a bien été modifié mais pas avec cette modif, c'est normal ?
> 
> Sinon, j'ai fait la modif du header, ca marche.

Bonjour, oui normal, tant que ma [pull request](https://github.com/Scrat95220/DomoticzGazpar/pull/38) n'est pas faite par l'auteur - Scrat95220 - ça ne marchera pas avec le code actuel, sauf à faire la correction à la main comme tu as fait.

**Comment by Holborn13200** [comment]
La correction est OK avec l'ajout dans le message header. Merci à tous ;)
