### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by alaunay** [Scrat95220/DomoticzGazpar#49]
Bonjour,

Depuis environ 48h, l'import ne fonctionne plus:

```
Traceback (most recent call last):
  File "/home/domoticz/DomoticzGazpar/gazpar.py", line 277, in <module>
    main()
  File "/home/domoticz/DomoticzGazpar/gazpar.py", line 268, in main
    update_counters(token, dtostr(today - relativedelta(days=int(nbDaysImported))), \
  File "/home/domoticz/DomoticzGazpar/gazpar.py", line 145, in update_counters
    index = j[str(numPce)]['releves'][0]['indexDebut']
TypeError: list indices must be integers or slices, not str
```

La connexion est bonne, mais sorti de ça... GRDF ne renvoie plus de données, peut-être ?

**Comment by Chaussette23** [comment]
J'ai le soucis également

**Comment by ricky074** [comment]
Hello, pareil pour moi ce matin...

**Comment by Chaussette23** [comment]
Le soucis venait du site GRDF qui a du avoir des modifications.

Attention, le problème est revenu quelques jours après, il y a besoin de changer le mot de passe du compte sur le site : [](https://monespace.grdf.fr/client/particulier/accueil)

**Comment by olpayras** [comment]
Bonjour,

Ca j'ai vu, on le voit direct quand on lance le script python. Hier soir cela ne fonctionnait pas malgré le changement de mot de passe et ce matin c'est passé.

Merci pour l'info. Donc à priori changer le mot de passe et être plus patient que moi... résout le problème.

**Comment by alaunay** [comment]
Ça a fini par bien remonter... Par contre, il y a toujours un truc qui déconne chez GRDF: pas de données depuis le 3 décembre, mais ni sur domoticz, ni chez eux. Pile poil quand on en a vraiment besoin, quoi...

**Comment by ricky074** [comment]
Tout pareil, plus de données depuis le 3 décembre...

**Comment by olpayras** [comment]
Effectivement, dernières informations collectées, journée du 3/12 chez moi. Depuis 0. A suivre.

**Comment by Phil353556** [comment]
Bonjour,
Faites un tour sur https://clients-ambassadeurs.grdf.fr/app/602/channel/accueil-923
aucune donnée disponible depuis le 3/4 décembre 2022 via GrDF
sans commentaire

**Comment by Overnuts** [comment]
Bonjour, on dirait que ça se débouche un peu chez grdf (dans leur interface tout du moins)
c'était resté à 3/12, et maintenant, j'ai aussi le 4 et le 6 (pas le 5)
j'ai remarqué que les index enkWh on un peu augmenté depuis le 3 nov, par rapport a ce que j'avais exporté, 
probablement un ajustement suite au coéf de conversion.

**Comment by olpayras** [comment]
Eureka, le 4/12 est arrivé... Mais pas les autres jours :(

**Comment by Phil353556** [comment]
cela semble revenu pour moi
