### ISSUE TITLE
KeyError: 'XLS_PATH'

### ISSUE THREAD

**Issue by djs45** [Scrat95220/DomoticzGazpar#56]
Hello
I have an error :

Traceback (most recent call last):
  File "./gazpar.py", line 358, in <module>
    main()
  File "./gazpar.py", line 330, in main
    get_config()
  File "./gazpar.py", line 242, in get_config
    xlsPath = config['GRDF']['XLS_PATH']
  File "/usr/lib/python3.7/configparser.py", line 1251, in __getitem__
    raise KeyError(key)
KeyError: 'XLS_PATH'

Note : I have reinstalled openpyxl because first error was "no module openpyxl"

Many thanks

**Comment by airvb** [comment]
pas mieux ...
```
~/DomoticzGazpar $ ./gazpar.py 
Login call - error status :REINPUT

Traceback (most recent call last):
  File "./gazpar.py", line 358, in <module>
    main()
  File "./gazpar.py", line 342, in main
    token = login()
  File "./gazpar.py", line 116, in login
    xlsimport()
  File "./gazpar.py", line 251, in xlsimport
    workbook = openpyxl.load_workbook(xlsPath)
  File "/home/pi/.local/lib/python3.7/site-packages/openpyxl/reader/excel.py", line 345, in load_workbook
    data_only, keep_links, rich_text)
  File "/home/pi/.local/lib/python3.7/site-packages/openpyxl/reader/excel.py", line 123, in __init__
    self.archive = _validate_archive(fn)
  File "/home/pi/.local/lib/python3.7/site-packages/openpyxl/reader/excel.py", line 93, in _validate_archive
    raise InvalidFileException(msg)
openpyxl.utils.exceptions.InvalidFileException: openpyxl does not support  file format, please check you can open it with Excel first. Supported formats are: .xlsx,.xlsm,.xltx,.xltm
``

**Comment by airvb** [comment]
Mais si ca fonctionne !
Je n'avais pas compris le :
XLS_PATH=path to your xlsx file imported

Il faut mettre le chemin et le nom du fichier !
ex `:XLS_PATH=/home/pi/data_gaz/test.xlsx`
