### ISSUE TITLE
Bad login is not detected

### ISSUE THREAD

**Issue by pbda** [Scrat95220/DomoticzGazpar#8]
If username or passwd is bad, program crashes with:
```
Traceback (most recent call last):
  File "./gazpar.py", line 193, in <module>
    main()
  File "./gazpar.py", line 182, in main
    dtostr(today))
  File "./gazpar.py", line 94, in generate_db_script
    j = json.loads(resp3.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
in log file, login seems OK:
```
2021-12-04 11:02:11,727 Get configuration
2021-12-04 11:02:11,729 logging in as xxx...
2021-12-04 11:02:12,139 logged in successfully!
2021-12-04 11:02:12,139 retrieving data...

```

**Comment by Scrat95220** [comment]
Corrected. Thanks
